- name: Instantiate {{ outer_loop.host_group }} root disk(s)
  gce_pd:
    zone: "{{ cloud_config.zone }}"
    name: "{{ cluster_name }}-{{ outer_loop.host_group }}{{ (outer_loop.count > 1) | ternary(local_loop,'') }}-os"
    disk_type: "{{ outer_loop.disks.root.type }}"
    size_gb: "{{ outer_loop.disks.root.size }}"
    snapshot: "{{ repos_os_snapshot }}"
    mode: READ_WRITE
    state: present
  loop_control:
    loop_var: local_loop
  with_sequence: count="{{ outer_loop.count }}" format=-%02x
  async: 1000
  poll: 0
  register: current_disks_async

- name: Wait for {{ outer_loop.host_group }} disk(s) to be created
  async_status:
    jid: "{{ local_loop.ansible_job_id }}"
  loop_control:
    loop_var: local_loop
  with_items: "{{ current_disks_async.results }}"
  register: current_disks
  until: current_disks.finished
  retries: 120

- name: Instantiate {{ outer_loop.host_group }} data disk(s)
  gce_pd:
    zone: "{{ cloud_config.zone }}"
    name: "{{ cluster_name }}-{{ outer_loop.host_group }}{{ (outer_loop.count > 1) | ternary(local_loop,'') }}-data"
    disk_type: "{{ outer_loop.disks.data.type }}"
    size_gb: "{{ outer_loop.disks.data.size }}"
    snapshot: "{{ repos_data_snapshot }}"
    mode: READ_WRITE
    state: present
  loop_control:
    loop_var: local_loop
  with_sequence: count="{{ outer_loop.count }}" format=-%02x
  async: 1000
  poll: 0
  register: current_disks_async
