- name: "Instantiate {{ outer_loop.host_group }} {{ disk.key }} disk"
  gce_pd:
    zone: "{{ cloud_config.zone }}"
    name: "{{ cluster_name }}-{{ outer_loop.host_group }}{{ (outer_loop.count > 1) | ternary(local_loop,'') }}-{{ disk.key }}"
    disk_type: "{{ disk.value.type }}"
    size_gb: "{{ disk.value.size }}"
    snapshot: "{{ disk.value.snapshot }}"
    mode: READ_WRITE
    state: present
  loop_control:
    loop_var: local_loop
  with_sequence: count="{{ outer_loop.count }}" format=-%02x
  async: 1000
  poll: 0
  register: current_disks_async

- name: "Wait for {{ outer_loop.host_group }} {{ disk.key }} disk to be created"
  async_status:
    jid: "{{ local_loop.ansible_job_id }}"
  loop_control:
    loop_var: local_loop
  with_items: "{{ current_disks_async.results }}"
  register: current_disks
  until: current_disks.finished
  retries: 120
