---
- name: "Build data filesystem for {{ outer_loop.host_group }}"
  delegate_to: "{{ (outer_loop.public_ip|default(false) == true) | ternary(local_loop.instance_data.0.public_ip,local_loop.instance_data.0.private_ip) }}"
  become: yes
  filesystem:
    dev: "{{ outer_loop.disks.data.device }}"
    fstype: ext4 # TODO confirm
    # TODO Any additional required parameters?
  loop_control:
    loop_var: local_loop
  with_items: '{{ current_nodes.results }}'

- name: "Mount data filesystems for {{ outer_loop.host_group }}"
  delegate_to: "{{ (outer_loop.public_ip|default(false) == true) | ternary(local_loop.instance_data.0.public_ip,local_loop.instance_data.0.private_ip) }}"
  become: yes
  mount:
    src: "{{ outer_loop.disks.data.device }}"
    fstype: ext4
    opts: defaults,noatime,nodiratime # TODO confirm
    path: "{{ '/data' if outer_loop.host_group == 'hdp-edge' else '/hadoop' }}"
    state: mounted
  loop_control:
    loop_var: local_loop
  with_items: '{{ current_nodes.results }}'
